###
# https://github.com/filebrowser/filebrowser
# https://github.com/jmeerschart/simple-file-upload-download-server
###
version: "3.8"
services:

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    hostname: upload-server
    volumes:
      - /etc/timezone:/etc/localtime:ro
      # - ./filebrowser/filebrowser.json:/.filebrowser.json
      # - ./filebrowser/database.db:/database.db
      # - ./data:/srv
      - data_volume:/srv
    ports:
      - 8080:80

  upload-server:
    image: julienmeerschart/simple-file-upload-download-server
    container_name: upload-server
    restart: unless-stopped
    hostname: upload-server
    environment:
      SERVER: "http://filebrowser:80"
    volumes:
      - /etc/timezone:/etc/localtime:ro
      #- ./data/uploads:/tmp
      - data_volume:/tmp
    depends_on:
      - filebrowser
    ports:
      - 3000:3000

###
# /var/lib/docker/volumes/<docker container directory name><volume name>/
volumes:
  data_volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind