version: '3.8'

services:
  blue-app:
    image: anti1346/demo:blue-green
    container_name: blue-app
    restart: on-failure
    hostname: blue-app
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
    ports:
      - "8081:8080"
    networks:
      - myapp-net

  green-app:
    image: anti1346/demo:blue-green
    container_name: green-app
    restart: on-failure
    hostname: green-app
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
    ports:
      - "8082:8080"
    networks:
      - myapp-net

  nginx:
    image: anti1346/nginx:blue-green
    container_name: nginx
    restart: on-failure
    hostname: nginx
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
    depends_on:
      - blue-app
      - green-app
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - myapp-net

networks:
  myapp-net:
    name: myapp-net
    driver: bridge