global:
  resolve_timeout: 5m
  slack_api_url: '${SLACK_API_URL}'

route:
  group_by: ['node_exporter']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 5m
  receiver: 'slack-notifications'
  routes:
  - receiver: 'slack-notifications'
    matchers:
      - alertname=~"InfoInhibitor|Watchdog"

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#${SLACK_API_CHANNEL}'
    send_resolved: true
    title: '[{{.Status | toUpper}}] {{ .CommonLabels.alertname }}'
    text: |
      *Description:* {{ .CommonAnnotations.description }}

